'on': push
name: Update-Disposals
jobs:
  update-rosters:
    name: Update-Disposals
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: '${{ secrets.GITHUB_TOKEN }}'
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: 'any:rcmdcheck'
      - name: Install fitZroy
        run: 'pak::pkg_install("jimmyday12/fitzRoy")'
        shell: 'Rscript{0}'
      - name: Update Disposals
        run: >-
          Rscript -e
          'source("afl_disposals_by_week/afldispbyweek/R/afl_disposals_by_week_git.R")'
