"on":
  schedule:
    - cron '0 0 16 ? 3-10 SUN,THU,FRI,SAT *'
name: Update-Disposals
jobs:
  update-rosters:
    name: Update-Disposals
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: "${{ secrets.GITHUB_TOKEN }}"
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
      - name: Update Disposals
        run: Rscript -e 'source("R/afl_disposals_by_week_git.R")'
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull
          git add -A
          git commit -m "Update data"  || echo "No changes to commit"
          git push origin main || echo "No changes to commit"

